### PR TITLE
Support SciPy 1.0.0

### LINKED ISSUE #130: Incompatible with scipy >=1.0 but requirements in setup.py do not capture this
* `import PyDSTool` fails due to bad scipy vers checking: see https://github.com/DiODeProject/MuMoT/issues/63
* references scipy function names deprecated in 1.0.0 e.g. `scipy.special.sph_*`

### PR DESCRIPTION
**Pull request by tkf**
First commit drops SciPy version check (>0.5.1). The oldest SciPy version hosted at https://docs.scipy.org/doc/ is 0.7 which is released at 2009. I don't think we need to guard against SciPy <= 0.5.0.  Also, `scipy>=0.9` is already included in setup.py so it is very tricky to install PyDSTool with SciPy <= 0.5.0 anyway.

Second commit replaces removed functions `scipy.special.sph_*` with `scipy.special.spherical_*`. See also:

> The deprecated functions sph_jn, sph_yn, sph_jnyn, sph_in, sph_kn, and sph_inkn have been removed. Users should instead use the functions spherical_jn, spherical_yn, spherical_in, and spherical_kn. Be aware that the new functions have different signatures.
> --- https://docs.scipy.org/doc/scipy/reference/release.1.0.0.html#backwards-incompatible-changes

When tested with `tox -e py36`, this pull request does not increase number of failed tests compared with #131.

Fixes #130.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@tkf do you think the best way to solve https://github.com/JuliaDiffEq/PyDSTool.jl/issues/5 for now is to just try upper bounding?

**Comment by freckletonj** [comment]
I just applied this patch to my local copy of `robclewley/pydstool` and it seems to be working thanks!

**Comment by dabliss** [comment]
what is the plan for this repo given that @robclewley seems not to be in a position anymore to make crucial updates to the package, such as this one?  is there any plan for succession?  as far as i know, this is the only major dynamical systems package for python . . . it seems silly that we're all stuck making local patches as the repo sits dormant.

**Comment by dabliss** [comment]
@ChrisRackauckas that's great!  many thanks for the heads up.  which repos should i be paying attention to?

**Comment by ChrisRackauckas** [comment]
there's not a good public thing to follow right now, other than maybe https://github.com/tkf/Bifurcations.jl . Right now we've been making sure to secure the resources. If we don't go @tkf's route then we'll be using deflation which doesn't require specializing on the types of bifurcations which, according to the literature, should make it a much much simpler project than previous arclength continuation-based software. So we are planning to build the repo cram it out with a bunch of students next summer (securing side funds right now, though it will likely be GSoC), but I won't guarantee that we will have it by 2019. In any case, JuliaDiffEq is rebranding to DiffEq with a big focus on making the tools Julia-based but cross-language compatible so whatever we do, maintaining bindings is on that list.

**Comment by tkf** [comment]
@ChrisRackauckas Interesting. What's the good introduction to deflation-based method? I didn't know about it.

**Comment by ChrisRackauckas** [comment]
http://people.maths.ox.ac.uk/beentjes/Essays/MScThesis2015-10.pdf
https://arxiv.org/abs/1603.00809

See the recent discussion in the Optim.jl Gitter as well for development plans/ideas.

**Comment by tkf** [comment]
Thanks a lot!

**Comment by dabliss** [comment]
in the meantime hopefully @robclewley will give authority to someone he trusts to make the basic updates needed to keep pydstool functional . . .

**Comment by robclewley** [comment]
Hi, thanks for your interest and patience. There was a loose agreement for
continued support from another group last year, but they haven't followed
up on their intent. Meanwhile, I'm working on getting someone's expertise
to fix the CI setup so that it's easier for me to work through the
outstanding PRs. If qualified users want to contribute directly to the
project in more substantial ways, message me about it. I don't have enough
experience with the theory of continuation to improve pycont, and I see
that's a primary interest to most users, so I particularly want help there.

**Comment by z2v** [comment]
Merged, thanks.

**Comment by willfurnass** [comment]
Thanks for this.  Can a new a new release be pushed to PyPI?

**Pull request merged**
