### PR TITLE
distutil_destination() fix for Max OS

### PR DESCRIPTION
**Pull request by tensionhead**
Works with Mac OS 10.10 and python 2.7, should work for all Mac OS >= 10.5, as the distutils.utils.get_platform() always returns minimal OS needed for numpy.distutils.core.setup, which is employed in CompileAutoLib() in ContClass.py. Maybe these adaptations should/could be done for the other supported OS (linux/windows) as well ?!

### CODE REVIEW

**Comment by z2v** [comment]
I've run tests and examples on FreeBSD-CURRENT. Works for me.

**Comment by robclewley** [comment]
Greg, could you make some kind of trivial change and commit it to this PR to re-trigger the Travis CI build tests, please? Vladimir has changed how these build scipy so they should function correctly now.

**Comment by z2v** [comment]
My changes exist only in [`improve/misctoolbox`](https://github.com/robclewley/pydstool/tree/improve/misctoolbox) branch. So I suggest do the following:

- @robclewley, you merge `improve/misctoolbox` in `master` and then 
- @tensionhead, you rebase your changes on updated `master` and recreate PR

**Comment by tensionhead** [comment]
Hey Guys,

sorry for my silent times, our ISP @home messed up..so I basically have to
work on PyDSTool when I am at work.
But I try to do this ASAP !

Vlad, so with rebase you mean I pull everything from updated master and
then recreate my Private Repository (PR),
redo the little changes and commit ?

Best,
G

**Comment by z2v** [comment]
PR == Pull Request

Pull changes from master branch of main repo to master branch of **your** repo, then rebase your changes on updated master and push them to your github fork.

**Comment by tensionhead** [comment]
Hey,

so sorry again for the delay.. I tried to follow vlads instructions, I am
not sure if I did it all correct. Can someone confirm that everything is ok
now ?!

Best,
Greg

**Pull request merged**
